GET http://localhost:8888/authorize?user=Bob&password=pass

###
GET http://localhost:8888/authorize?user=Bb&password=pass

###
GET http://localhost:8888/authorize?user=Bob&password=pss

###

GET http://localhost:8888/authorize?user=&password=

###